# Generated by Django 5.1.1 on 2024-09-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogentry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogentry",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубликовано"),
        ),
        migrations.AlterField(
            model_name="blogentry",
            name="slug",
            field=models.CharField(max_length=150, unique=True, verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="blogentry",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="Количество просмотров"),
        ),
    ]
