# Generated by Django 5.1.1 on 2024-09-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "blogentry",
            "0002_alter_blogentry_is_published_alter_blogentry_slug_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogentry",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Опубликовано"),
        ),
    ]
