# Generated by Django 5.1.1 on 2024-09-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_version"),
        ("catalog", "0003_product_owner"),
    ]

    operations = []
