# Generated by Django 5.1.1 on 2024-09-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_merge_0002_version_0003_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("can_unpublish_product", "Может отменить публикацию продукта"),
                    (
                        "can_change_any_product",
                        "Может изменять описание любого продукта",
                    ),
                    ("can_change_category", "Может изменять категорию любого продукта"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("draft", "Черновик"), ("published", "Опубликован")],
                default="draft",
                max_length=10,
                verbose_name="Статус публикации",
            ),
        ),
        migrations.DeleteModel(
            name="Version",
        ),
    ]
